module.exports = {
    OK: 'OK',
    FAILED: 'FAILED',
    MISSING_DATA: 'MISSING_DATA',
    INVALID_DATA: 'INVALID_DATA',
    FAILED_UNIQUE_EMAIL: 'FAILED_UNIQUE_EMAIL',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    INVALID_TOKEN_FORMAT: 'INVALID_TOKEN_FORMAT',
    ACCESS_DENIED: 'ACCESS_DENIED',
};
